backend:
  name: github
  repo: graemebenzie/continuasolutions.com # Path to your Github repository
  branch: release # Branch to update
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
site_id: continuasolutions.netlify.com
collections:
  - name: "slider" # Used in routes, e.g., /admin/collections/blog
    label: "Slider" # Used in the UI
    folder: "content/slider" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter 
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Exclude from Sitemap", name: "excludeFromSiteMap", widget: "hidden", default: true} 
      - {label: "Heading", name: "heading", widget: "string"}      
      - {label: "Sub Heading", name: "subheading", widget: "string"}      
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"} 
  - name: "team" # Used in routes, e.g., /admin/collections/blog
    label: "Team" # Used in the UI
    folder: "content/team" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter      
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Degree Letters", name: "degreeletters", widget: "string"}      
      - {label: "Job Title", name: "jobtitle", widget: "string"}      
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Blurb", name: "blurb", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}  
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter      
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub Title", name: "subtitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "clients" # Used in routes, e.g., /admin/collections/blog
    label: "Clients" # Used in the UI
    folder: "content/clients" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Job Title", name: "jobtitle", widget: "string"}  
      - {label: "Project", name: "project", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}      
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}              
      - {label: "Exclude from Sitemap", name: "excludeFromSiteMap", widget: "hidden", default: true} 